services:
  - type: web
    name: api-rendement-agricole-cameroun
    runtime: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
